name="张三"
age=18
height=178.5
is_student=True
print("姓名:",name)
print("年龄:",age)
print("年龄的数据类型：",type(age))
print("身高:",height)
print("是否为学生:",is_student)
city="北京"
score=95.5
print(f"我叫{name},我住在{city}，我的成绩是{score}.")
next_age=age+1
print(f"我的年龄是{age}，明年我将是{next_age}岁。")
gender="男"
job="程序员"
salary=15000.0 
print(f"我叫{name},性别{gender},今年{age}岁,是一名{job},月薪{salary}元。")
#/如何定义变量以及f-string的用法